import {
  PROVIDERS,
  type ContentBlock,
  type GlobalSettingsUpdateRequest,
  type GlobalSettingsView,
  type ProjectAddRequest,
  type ProjectListView,
  type ProjectRemoveRequest,
  type ProjectRow,
  type ProjectSuggestion,
  type ProjectSuggestionsQuery,
  type ProjectSuggestionsView,
  type ProjectUpdateRequest,
  type ProviderId,
  type SessionHistoryRequest,
  type SessionHistoryWindow,
  type SessionNewRequest,
  type SessionNewResult,
  type SessionOpenResult,
  type SessionOpenRequest,
  type SessionPromptRequest,
  type ProvidersConfigSnapshotResult,
  type SessionConfigOption,
  type SessionGroupsQuery,
  type SessionGroupsView,
  type SessionSetConfigOptionRequest,
  type SessionSetConfigOptionResult,
  type TranscriptItem,
} from "@conduit/app-protocol";
import type {
  SessionTimelineChanged,
  SessionsIndexChanged,
} from "./timelineEvent.js";
import type {
  SessionClientOptions,
  SessionClientPort,
  SessionClientTelemetryEvent,
} from "./sessionClientPort.js";
import { createSessionClient } from "./createSessionClient.js";
import { WebSocketSessionClient } from "./webSocketSessionClient.js";

export {
  createSessionClient,
  WebSocketSessionClient,
  PROVIDERS,
  type ContentBlock,
  type GlobalSettingsUpdateRequest,
  type GlobalSettingsView,
  type ProjectAddRequest,
  type ProjectListView,
  type ProjectRemoveRequest,
  type ProjectRow,
  type ProjectSuggestion,
  type ProjectSuggestionsQuery,
  type ProjectSuggestionsView,
  type ProjectUpdateRequest,
  type ProviderId,
  type ProvidersConfigSnapshotResult,
  type SessionClientOptions,
  type SessionClientPort,
  type SessionClientTelemetryEvent,
  type SessionConfigOption,
  type SessionGroupsQuery,
  type SessionGroupsView,
  type SessionHistoryRequest,
  type SessionHistoryWindow,
  type SessionNewRequest,
  type SessionNewResult,
  type SessionOpenRequest,
  type SessionOpenResult,
  type SessionPromptRequest,
  type SessionSetConfigOptionRequest,
  type SessionSetConfigOptionResult,
  type SessionTimelineChanged,
  type SessionsIndexChanged,
  type TranscriptItem,
};
