// This file is generated by `pnpm run protocol:generate`.
// Do not edit manually.
/* eslint-disable max-lines */
import { z } from "zod";

const PROTOCOL_CONTRACT_VERSION = 1 as const;

// prettier-ignore
const AcpMetaSchema = z.record(z.string(), z.unknown());
// prettier-ignore
type AcpMeta = z.infer<typeof AcpMetaSchema>;

// prettier-ignore
const AcpTextContentSchema = z.object({
  type: z.literal("text"),
  annotations: z.unknown().optional().nullable(),
  text: z.string(),
  _meta: AcpMetaSchema.optional().nullable()
});
// prettier-ignore
type AcpTextContent = z.infer<typeof AcpTextContentSchema>;

// prettier-ignore
const AcpImageContentSchema = z.object({
  type: z.literal("image"),
  annotations: z.unknown().optional().nullable(),
  data: z.string(),
  mimeType: z.string(),
  uri: z.string().optional().nullable(),
  _meta: AcpMetaSchema.optional().nullable()
});
// prettier-ignore
type AcpImageContent = z.infer<typeof AcpImageContentSchema>;

// prettier-ignore
const AcpAudioContentSchema = z.object({
  type: z.literal("audio"),
  annotations: z.unknown().optional().nullable(),
  data: z.string(),
  mimeType: z.string(),
  _meta: AcpMetaSchema.optional().nullable()
});
// prettier-ignore
type AcpAudioContent = z.infer<typeof AcpAudioContentSchema>;

// prettier-ignore
const AcpResourceLinkContentSchema = z.object({
  type: z.literal("resource_link"),
  annotations: z.unknown().optional().nullable(),
  name: z.string(),
  uri: z.string(),
  description: z.string().optional().nullable(),
  mimeType: z.string().optional().nullable(),
  _meta: AcpMetaSchema.optional().nullable()
});
// prettier-ignore
type AcpResourceLinkContent = z.infer<typeof AcpResourceLinkContentSchema>;

// prettier-ignore
const AcpEmbeddedResourceContentSchema = z.object({
  type: z.literal("resource"),
  annotations: z.unknown().optional().nullable(),
  resource: z.unknown(),
  _meta: AcpMetaSchema.optional().nullable()
});
// prettier-ignore
type AcpEmbeddedResourceContent = z.infer<typeof AcpEmbeddedResourceContentSchema>;

// prettier-ignore
const AcpContentBlockSchema = z.discriminatedUnion("type", [
  AcpTextContentSchema,
  AcpImageContentSchema,
  AcpAudioContentSchema,
  AcpResourceLinkContentSchema,
  AcpEmbeddedResourceContentSchema
]);
// prettier-ignore
type AcpContentBlock = z.infer<typeof AcpContentBlockSchema>;

// prettier-ignore
const AcpContentChunkSchema = z.object({
  content: AcpContentBlockSchema,
  messageId: z.string().optional().nullable(),
  _meta: AcpMetaSchema.optional().nullable()
});
// prettier-ignore
type AcpContentChunk = z.infer<typeof AcpContentChunkSchema>;

// prettier-ignore
const AcpToolKindSchema = z.union([z.literal("read"), z.literal("edit"), z.literal("delete"), z.literal("move"), z.literal("search"), z.literal("execute"), z.literal("think"), z.literal("fetch"), z.literal("switch_mode"), z.literal("other")]);
// prettier-ignore
type AcpToolKind = z.infer<typeof AcpToolKindSchema>;

// prettier-ignore
const AcpToolCallStatusSchema = z.union([z.literal("pending"), z.literal("in_progress"), z.literal("completed"), z.literal("failed")]);
// prettier-ignore
type AcpToolCallStatus = z.infer<typeof AcpToolCallStatusSchema>;

// prettier-ignore
const AcpToolCallContentSchema = z.discriminatedUnion("type", [
  z.object({
    type: z.literal("content"),
    content: AcpContentBlockSchema,
    _meta: AcpMetaSchema.optional().nullable()
  }),
  z.object({
    type: z.literal("diff"),
    path: z.string(),
    oldText: z.string().optional().nullable(),
    newText: z.string(),
    _meta: AcpMetaSchema.optional().nullable()
  }),
  z.object({
    type: z.literal("terminal"),
    terminalId: z.string(),
    _meta: AcpMetaSchema.optional().nullable()
  })
]);
// prettier-ignore
type AcpToolCallContent = z.infer<typeof AcpToolCallContentSchema>;

// prettier-ignore
const AcpToolCallLocationSchema = z.object({
  path: z.string(),
  line: z.number().int().nonnegative().optional().nullable(),
  _meta: AcpMetaSchema.optional().nullable()
});
// prettier-ignore
type AcpToolCallLocation = z.infer<typeof AcpToolCallLocationSchema>;

// prettier-ignore
const AcpToolCallSchema = z.object({
  toolCallId: z.string(),
  title: z.string(),
  kind: AcpToolKindSchema.optional(),
  status: AcpToolCallStatusSchema.optional(),
  content: z.array(AcpToolCallContentSchema).optional(),
  locations: z.array(AcpToolCallLocationSchema).optional(),
  rawInput: z.unknown().optional().nullable(),
  rawOutput: z.unknown().optional().nullable(),
  _meta: AcpMetaSchema.optional().nullable()
});
// prettier-ignore
type AcpToolCall = z.infer<typeof AcpToolCallSchema>;

// prettier-ignore
const AcpToolCallUpdateSchema = z.object({
  toolCallId: z.string(),
  kind: AcpToolKindSchema.optional().nullable(),
  status: AcpToolCallStatusSchema.optional().nullable(),
  title: z.string().optional().nullable(),
  content: z.array(AcpToolCallContentSchema).optional().nullable(),
  locations: z.array(AcpToolCallLocationSchema).optional().nullable(),
  rawInput: z.unknown().optional().nullable(),
  rawOutput: z.unknown().optional().nullable(),
  _meta: AcpMetaSchema.optional().nullable()
});
// prettier-ignore
type AcpToolCallUpdate = z.infer<typeof AcpToolCallUpdateSchema>;

// prettier-ignore
const AcpPlanEntryPrioritySchema = z.union([z.literal("high"), z.literal("medium"), z.literal("low")]);
// prettier-ignore
type AcpPlanEntryPriority = z.infer<typeof AcpPlanEntryPrioritySchema>;

// prettier-ignore
const AcpPlanEntryStatusSchema = z.union([z.literal("pending"), z.literal("in_progress"), z.literal("completed")]);
// prettier-ignore
type AcpPlanEntryStatus = z.infer<typeof AcpPlanEntryStatusSchema>;

// prettier-ignore
const AcpPlanEntrySchema = z.object({
  content: z.string(),
  priority: AcpPlanEntryPrioritySchema,
  status: AcpPlanEntryStatusSchema,
  _meta: AcpMetaSchema.optional().nullable()
});
// prettier-ignore
type AcpPlanEntry = z.infer<typeof AcpPlanEntrySchema>;

// prettier-ignore
const AcpPlanSchema = z.object({
  entries: z.array(AcpPlanEntrySchema),
  _meta: AcpMetaSchema.optional().nullable()
});
// prettier-ignore
type AcpPlan = z.infer<typeof AcpPlanSchema>;

// prettier-ignore
const AcpAvailableCommandInputSchema = z.object({
  hint: z.string(),
  _meta: AcpMetaSchema.optional().nullable()
});
// prettier-ignore
type AcpAvailableCommandInput = z.infer<typeof AcpAvailableCommandInputSchema>;

// prettier-ignore
const AcpAvailableCommandSchema = z.object({
  name: z.string(),
  description: z.string(),
  input: AcpAvailableCommandInputSchema.optional().nullable(),
  _meta: AcpMetaSchema.optional().nullable()
});
// prettier-ignore
type AcpAvailableCommand = z.infer<typeof AcpAvailableCommandSchema>;

// prettier-ignore
const AcpAvailableCommandsUpdateSchema = z.object({
  availableCommands: z.array(AcpAvailableCommandSchema),
  _meta: AcpMetaSchema.optional().nullable()
});
// prettier-ignore
type AcpAvailableCommandsUpdate = z.infer<typeof AcpAvailableCommandsUpdateSchema>;

// prettier-ignore
const AcpCurrentModeUpdateSchema = z.object({
  currentModeId: z.string(),
  _meta: AcpMetaSchema.optional().nullable()
});
// prettier-ignore
type AcpCurrentModeUpdate = z.infer<typeof AcpCurrentModeUpdateSchema>;

// prettier-ignore
const AcpConfigOptionUpdateSchema = z.object({
  configOptions: z.array(z.record(z.string(), z.unknown())),
  _meta: AcpMetaSchema.optional().nullable()
});
// prettier-ignore
type AcpConfigOptionUpdate = z.infer<typeof AcpConfigOptionUpdateSchema>;

// prettier-ignore
const AcpSessionInfoUpdateSchema = z.object({
  title: z.string().optional().nullable(),
  updatedAt: z.string().optional().nullable(),
  _meta: AcpMetaSchema.optional().nullable()
});
// prettier-ignore
type AcpSessionInfoUpdate = z.infer<typeof AcpSessionInfoUpdateSchema>;

// prettier-ignore
const AcpSessionUpdateSchema = z.discriminatedUnion("sessionUpdate", [
  AcpContentChunkSchema.extend({ sessionUpdate: z.literal("user_message_chunk") }),
  AcpContentChunkSchema.extend({ sessionUpdate: z.literal("agent_message_chunk") }),
  AcpContentChunkSchema.extend({ sessionUpdate: z.literal("agent_thought_chunk") }),
  AcpToolCallSchema.extend({ sessionUpdate: z.literal("tool_call") }),
  AcpToolCallUpdateSchema.extend({ sessionUpdate: z.literal("tool_call_update") }),
  AcpPlanSchema.extend({ sessionUpdate: z.literal("plan") }),
  AcpAvailableCommandsUpdateSchema.extend({ sessionUpdate: z.literal("available_commands_update") }),
  AcpCurrentModeUpdateSchema.extend({ sessionUpdate: z.literal("current_mode_update") }),
  AcpConfigOptionUpdateSchema.extend({ sessionUpdate: z.literal("config_option_update") }),
  AcpSessionInfoUpdateSchema.extend({ sessionUpdate: z.literal("session_info_update") })
]);
// prettier-ignore
type AcpSessionUpdate = z.infer<typeof AcpSessionUpdateSchema>;

export {
  PROTOCOL_CONTRACT_VERSION,
  AcpMetaSchema,
  AcpTextContentSchema,
  AcpImageContentSchema,
  AcpAudioContentSchema,
  AcpResourceLinkContentSchema,
  AcpEmbeddedResourceContentSchema,
  AcpContentBlockSchema,
  AcpContentChunkSchema,
  AcpToolKindSchema,
  AcpToolCallStatusSchema,
  AcpToolCallContentSchema,
  AcpToolCallLocationSchema,
  AcpToolCallSchema,
  AcpToolCallUpdateSchema,
  AcpPlanEntryPrioritySchema,
  AcpPlanEntryStatusSchema,
  AcpPlanEntrySchema,
  AcpPlanSchema,
  AcpAvailableCommandInputSchema,
  AcpAvailableCommandSchema,
  AcpAvailableCommandsUpdateSchema,
  AcpCurrentModeUpdateSchema,
  AcpConfigOptionUpdateSchema,
  AcpSessionInfoUpdateSchema,
  AcpSessionUpdateSchema,
};

export type {
  AcpMeta,
  AcpTextContent,
  AcpImageContent,
  AcpAudioContent,
  AcpResourceLinkContent,
  AcpEmbeddedResourceContent,
  AcpContentBlock,
  AcpContentChunk,
  AcpToolKind,
  AcpToolCallStatus,
  AcpToolCallContent,
  AcpToolCallLocation,
  AcpToolCall,
  AcpToolCallUpdate,
  AcpPlanEntryPriority,
  AcpPlanEntryStatus,
  AcpPlanEntry,
  AcpPlan,
  AcpAvailableCommandInput,
  AcpAvailableCommand,
  AcpAvailableCommandsUpdate,
  AcpCurrentModeUpdate,
  AcpConfigOptionUpdate,
  AcpSessionInfoUpdate,
  AcpSessionUpdate,
};
