import { conduitApi } from "./api";

const {
  useAddProjectMutation,
  useGetProjectSuggestionsQuery,
  useGetProvidersConfigSnapshotQuery,
  useGetRuntimeHealthQuery,
  useGetSessionGroupsQuery,
  useGetSettingsQuery,
  useListProjectsQuery,
  useLoadOlderSessionTimelineMutation,
  useNewSessionMutation,
  useOpenSessionMutation,
  usePromptSessionMutation,
  useReadSessionTimelineQuery,
  useRemoveProjectMutation,
  useRespondInteractionMutation,
  useSetSessionConfigOptionMutation,
  useUpdateProjectMutation,
  useUpdateSettingsMutation,
} = conduitApi;

export {
  useAddProjectMutation,
  useGetProjectSuggestionsQuery,
  useGetProvidersConfigSnapshotQuery,
  useGetRuntimeHealthQuery,
  useGetSessionGroupsQuery,
  useGetSettingsQuery,
  useListProjectsQuery,
  useLoadOlderSessionTimelineMutation,
  useNewSessionMutation,
  useOpenSessionMutation,
  usePromptSessionMutation,
  useReadSessionTimelineQuery,
  useRemoveProjectMutation,
  useRespondInteractionMutation,
  useSetSessionConfigOptionMutation,
  useUpdateProjectMutation,
  useUpdateSettingsMutation,
};
