//! Contract schemas emitted into `packages/app-protocol`.

use zod_gen::ZodSchema;

const SCHEMA_EXPORTS: [&str; 26] = [
    "PROTOCOL_CONTRACT_VERSION",
    "AcpMetaSchema",
    "AcpTextContentSchema",
    "AcpImageContentSchema",
    "AcpAudioContentSchema",
    "AcpResourceLinkContentSchema",
    "AcpEmbeddedResourceContentSchema",
    "AcpContentBlockSchema",
    "AcpContentChunkSchema",
    "AcpToolKindSchema",
    "AcpToolCallStatusSchema",
    "AcpToolCallContentSchema",
    "AcpToolCallLocationSchema",
    "AcpToolCallSchema",
    "AcpToolCallUpdateSchema",
    "AcpPlanEntryPrioritySchema",
    "AcpPlanEntryStatusSchema",
    "AcpPlanEntrySchema",
    "AcpPlanSchema",
    "AcpAvailableCommandInputSchema",
    "AcpAvailableCommandSchema",
    "AcpAvailableCommandsUpdateSchema",
    "AcpCurrentModeUpdateSchema",
    "AcpConfigOptionUpdateSchema",
    "AcpSessionInfoUpdateSchema",
    "AcpSessionUpdateSchema",
];

const TYPE_EXPORTS: [&str; 25] = [
    "AcpMeta",
    "AcpTextContent",
    "AcpImageContent",
    "AcpAudioContent",
    "AcpResourceLinkContent",
    "AcpEmbeddedResourceContent",
    "AcpContentBlock",
    "AcpContentChunk",
    "AcpToolKind",
    "AcpToolCallStatus",
    "AcpToolCallContent",
    "AcpToolCallLocation",
    "AcpToolCall",
    "AcpToolCallUpdate",
    "AcpPlanEntryPriority",
    "AcpPlanEntryStatus",
    "AcpPlanEntry",
    "AcpPlan",
    "AcpAvailableCommandInput",
    "AcpAvailableCommand",
    "AcpAvailableCommandsUpdate",
    "AcpCurrentModeUpdate",
    "AcpConfigOptionUpdate",
    "AcpSessionInfoUpdate",
    "AcpSessionUpdate",
];

pub(crate) fn generate_typescript() -> String {
    let mut output = String::from(
        r#"// This file is generated by `pnpm run protocol:generate`.
// Do not edit manually.
/* eslint-disable max-lines */
import { z } from "zod";

const PROTOCOL_CONTRACT_VERSION = 1 as const;

"#,
    );

    push_schema::<AcpMeta>(&mut output, "AcpMeta");
    push_schema::<AcpTextContent>(&mut output, "AcpTextContent");
    push_schema::<AcpImageContent>(&mut output, "AcpImageContent");
    push_schema::<AcpAudioContent>(&mut output, "AcpAudioContent");
    push_schema::<AcpResourceLinkContent>(&mut output, "AcpResourceLinkContent");
    push_schema::<AcpEmbeddedResourceContent>(&mut output, "AcpEmbeddedResourceContent");
    push_schema::<AcpContentBlock>(&mut output, "AcpContentBlock");
    push_schema::<AcpContentChunk>(&mut output, "AcpContentChunk");
    push_schema::<AcpToolKind>(&mut output, "AcpToolKind");
    push_schema::<AcpToolCallStatus>(&mut output, "AcpToolCallStatus");
    push_schema::<AcpToolCallContent>(&mut output, "AcpToolCallContent");
    push_schema::<AcpToolCallLocation>(&mut output, "AcpToolCallLocation");
    push_schema::<AcpToolCall>(&mut output, "AcpToolCall");
    push_schema::<AcpToolCallUpdate>(&mut output, "AcpToolCallUpdate");
    push_schema::<AcpPlanEntryPriority>(&mut output, "AcpPlanEntryPriority");
    push_schema::<AcpPlanEntryStatus>(&mut output, "AcpPlanEntryStatus");
    push_schema::<AcpPlanEntry>(&mut output, "AcpPlanEntry");
    push_schema::<AcpPlan>(&mut output, "AcpPlan");
    push_schema::<AcpAvailableCommandInput>(&mut output, "AcpAvailableCommandInput");
    push_schema::<AcpAvailableCommand>(&mut output, "AcpAvailableCommand");
    push_schema::<AcpAvailableCommandsUpdate>(&mut output, "AcpAvailableCommandsUpdate");
    push_schema::<AcpCurrentModeUpdate>(&mut output, "AcpCurrentModeUpdate");
    push_schema::<AcpConfigOptionUpdate>(&mut output, "AcpConfigOptionUpdate");
    push_schema::<AcpSessionInfoUpdate>(&mut output, "AcpSessionInfoUpdate");
    push_schema::<AcpSessionUpdate>(&mut output, "AcpSessionUpdate");
    push_export_block(&mut output, "export", &SCHEMA_EXPORTS);
    push_export_block(&mut output, "export type", &TYPE_EXPORTS);

    if output.ends_with("\n\n") {
        output.truncate(output.len() - 1);
    }
    output
}

fn push_schema<T: ZodSchema>(output: &mut String, name: &str) {
    output.push_str("// prettier-ignore\n");
    output.push_str("const ");
    output.push_str(name);
    output.push_str("Schema = ");
    output.push_str(&T::zod_schema());
    output.push_str(";\n// prettier-ignore\ntype ");
    output.push_str(name);
    output.push_str(" = z.infer<typeof ");
    output.push_str(name);
    output.push_str("Schema>;\n\n");
}

fn push_export_block(output: &mut String, keyword: &str, names: &[&str]) {
    output.push_str(keyword);
    output.push_str(" {\n");
    for name in names {
        output.push_str("  ");
        output.push_str(name);
        output.push_str(",\n");
    }
    output.push_str("};\n\n");
}

struct AcpMeta;

impl ZodSchema for AcpMeta {
    fn zod_schema() -> String {
        "z.record(z.string(), z.unknown())".to_owned()
    }
}

struct AcpTextContent;

impl ZodSchema for AcpTextContent {
    fn zod_schema() -> String {
        object_schema(&[
            ("type", r#"z.literal("text")"#),
            ("annotations", optional_unknown()),
            ("text", "z.string()"),
            ("_meta", optional_meta()),
        ])
    }
}

struct AcpImageContent;

impl ZodSchema for AcpImageContent {
    fn zod_schema() -> String {
        object_schema(&[
            ("type", r#"z.literal("image")"#),
            ("annotations", optional_unknown()),
            ("data", "z.string()"),
            ("mimeType", "z.string()"),
            ("uri", "z.string().optional().nullable()"),
            ("_meta", optional_meta()),
        ])
    }
}

struct AcpAudioContent;

impl ZodSchema for AcpAudioContent {
    fn zod_schema() -> String {
        object_schema(&[
            ("type", r#"z.literal("audio")"#),
            ("annotations", optional_unknown()),
            ("data", "z.string()"),
            ("mimeType", "z.string()"),
            ("_meta", optional_meta()),
        ])
    }
}

struct AcpResourceLinkContent;

impl ZodSchema for AcpResourceLinkContent {
    fn zod_schema() -> String {
        object_schema(&[
            ("type", r#"z.literal("resource_link")"#),
            ("annotations", optional_unknown()),
            ("name", "z.string()"),
            ("uri", "z.string()"),
            ("description", "z.string().optional().nullable()"),
            ("mimeType", "z.string().optional().nullable()"),
            ("_meta", optional_meta()),
        ])
    }
}

struct AcpEmbeddedResourceContent;

impl ZodSchema for AcpEmbeddedResourceContent {
    fn zod_schema() -> String {
        object_schema(&[
            ("type", r#"z.literal("resource")"#),
            ("annotations", optional_unknown()),
            ("resource", "z.unknown()"),
            ("_meta", optional_meta()),
        ])
    }
}

struct AcpContentBlock;

impl ZodSchema for AcpContentBlock {
    fn zod_schema() -> String {
        r#"z.discriminatedUnion("type", [
  AcpTextContentSchema,
  AcpImageContentSchema,
  AcpAudioContentSchema,
  AcpResourceLinkContentSchema,
  AcpEmbeddedResourceContentSchema
])"#
        .to_owned()
    }
}

struct AcpContentChunk;

impl ZodSchema for AcpContentChunk {
    fn zod_schema() -> String {
        object_schema(&[
            ("content", "AcpContentBlockSchema"),
            ("messageId", "z.string().optional().nullable()"),
            ("_meta", optional_meta()),
        ])
    }
}

struct AcpToolKind;

impl ZodSchema for AcpToolKind {
    fn zod_schema() -> String {
        literal_union(&[
            "read",
            "edit",
            "delete",
            "move",
            "search",
            "execute",
            "think",
            "fetch",
            "switch_mode",
            "other",
        ])
    }
}

struct AcpToolCallStatus;

impl ZodSchema for AcpToolCallStatus {
    fn zod_schema() -> String {
        literal_union(&["pending", "in_progress", "completed", "failed"])
    }
}

struct AcpToolCallContent;

impl ZodSchema for AcpToolCallContent {
    fn zod_schema() -> String {
        r#"z.discriminatedUnion("type", [
  z.object({
    type: z.literal("content"),
    content: AcpContentBlockSchema,
    _meta: AcpMetaSchema.optional().nullable()
  }),
  z.object({
    type: z.literal("diff"),
    path: z.string(),
    oldText: z.string().optional().nullable(),
    newText: z.string(),
    _meta: AcpMetaSchema.optional().nullable()
  }),
  z.object({
    type: z.literal("terminal"),
    terminalId: z.string(),
    _meta: AcpMetaSchema.optional().nullable()
  })
])"#
        .to_owned()
    }
}

struct AcpToolCallLocation;

impl ZodSchema for AcpToolCallLocation {
    fn zod_schema() -> String {
        object_schema(&[
            ("path", "z.string()"),
            (
                "line",
                "z.number().int().nonnegative().optional().nullable()",
            ),
            ("_meta", optional_meta()),
        ])
    }
}

struct AcpToolCall;

impl ZodSchema for AcpToolCall {
    fn zod_schema() -> String {
        object_schema(&[
            ("toolCallId", "z.string()"),
            ("title", "z.string()"),
            ("kind", "AcpToolKindSchema.optional()"),
            ("status", "AcpToolCallStatusSchema.optional()"),
            ("content", "z.array(AcpToolCallContentSchema).optional()"),
            ("locations", "z.array(AcpToolCallLocationSchema).optional()"),
            ("rawInput", "z.unknown().optional().nullable()"),
            ("rawOutput", "z.unknown().optional().nullable()"),
            ("_meta", optional_meta()),
        ])
    }
}

struct AcpToolCallUpdate;

impl ZodSchema for AcpToolCallUpdate {
    fn zod_schema() -> String {
        object_schema(&[
            ("toolCallId", "z.string()"),
            ("kind", "AcpToolKindSchema.optional().nullable()"),
            ("status", "AcpToolCallStatusSchema.optional().nullable()"),
            ("title", "z.string().optional().nullable()"),
            (
                "content",
                "z.array(AcpToolCallContentSchema).optional().nullable()",
            ),
            (
                "locations",
                "z.array(AcpToolCallLocationSchema).optional().nullable()",
            ),
            ("rawInput", "z.unknown().optional().nullable()"),
            ("rawOutput", "z.unknown().optional().nullable()"),
            ("_meta", optional_meta()),
        ])
    }
}

struct AcpPlanEntryPriority;

impl ZodSchema for AcpPlanEntryPriority {
    fn zod_schema() -> String {
        literal_union(&["high", "medium", "low"])
    }
}

struct AcpPlanEntryStatus;

impl ZodSchema for AcpPlanEntryStatus {
    fn zod_schema() -> String {
        literal_union(&["pending", "in_progress", "completed"])
    }
}

struct AcpPlanEntry;

impl ZodSchema for AcpPlanEntry {
    fn zod_schema() -> String {
        object_schema(&[
            ("content", "z.string()"),
            ("priority", "AcpPlanEntryPrioritySchema"),
            ("status", "AcpPlanEntryStatusSchema"),
            ("_meta", optional_meta()),
        ])
    }
}

struct AcpPlan;

impl ZodSchema for AcpPlan {
    fn zod_schema() -> String {
        object_schema(&[
            ("entries", "z.array(AcpPlanEntrySchema)"),
            ("_meta", optional_meta()),
        ])
    }
}

struct AcpAvailableCommandInput;

impl ZodSchema for AcpAvailableCommandInput {
    fn zod_schema() -> String {
        object_schema(&[("hint", "z.string()"), ("_meta", optional_meta())])
    }
}

struct AcpAvailableCommand;

impl ZodSchema for AcpAvailableCommand {
    fn zod_schema() -> String {
        object_schema(&[
            ("name", "z.string()"),
            ("description", "z.string()"),
            (
                "input",
                "AcpAvailableCommandInputSchema.optional().nullable()",
            ),
            ("_meta", optional_meta()),
        ])
    }
}

struct AcpAvailableCommandsUpdate;

impl ZodSchema for AcpAvailableCommandsUpdate {
    fn zod_schema() -> String {
        object_schema(&[
            ("availableCommands", "z.array(AcpAvailableCommandSchema)"),
            ("_meta", optional_meta()),
        ])
    }
}

struct AcpCurrentModeUpdate;

impl ZodSchema for AcpCurrentModeUpdate {
    fn zod_schema() -> String {
        object_schema(&[("currentModeId", "z.string()"), ("_meta", optional_meta())])
    }
}

struct AcpConfigOptionUpdate;

impl ZodSchema for AcpConfigOptionUpdate {
    fn zod_schema() -> String {
        object_schema(&[
            (
                "configOptions",
                "z.array(z.record(z.string(), z.unknown()))",
            ),
            ("_meta", optional_meta()),
        ])
    }
}

struct AcpSessionInfoUpdate;

impl ZodSchema for AcpSessionInfoUpdate {
    fn zod_schema() -> String {
        object_schema(&[
            ("title", "z.string().optional().nullable()"),
            ("updatedAt", "z.string().optional().nullable()"),
            ("_meta", optional_meta()),
        ])
    }
}

struct AcpSessionUpdate;

impl ZodSchema for AcpSessionUpdate {
    fn zod_schema() -> String {
        r#"z.discriminatedUnion("sessionUpdate", [
  AcpContentChunkSchema.extend({ sessionUpdate: z.literal("user_message_chunk") }),
  AcpContentChunkSchema.extend({ sessionUpdate: z.literal("agent_message_chunk") }),
  AcpContentChunkSchema.extend({ sessionUpdate: z.literal("agent_thought_chunk") }),
  AcpToolCallSchema.extend({ sessionUpdate: z.literal("tool_call") }),
  AcpToolCallUpdateSchema.extend({ sessionUpdate: z.literal("tool_call_update") }),
  AcpPlanSchema.extend({ sessionUpdate: z.literal("plan") }),
  AcpAvailableCommandsUpdateSchema.extend({ sessionUpdate: z.literal("available_commands_update") }),
  AcpCurrentModeUpdateSchema.extend({ sessionUpdate: z.literal("current_mode_update") }),
  AcpConfigOptionUpdateSchema.extend({ sessionUpdate: z.literal("config_option_update") }),
  AcpSessionInfoUpdateSchema.extend({ sessionUpdate: z.literal("session_info_update") })
])"#
        .to_owned()
    }
}

fn object_schema(fields: &[(&str, &str)]) -> String {
    let fields = fields
        .iter()
        .map(|(name, schema)| format!("  {name}: {schema}"))
        .collect::<Vec<_>>()
        .join(",\n");
    format!("z.object({{\n{fields}\n}})")
}

fn literal_union(values: &[&str]) -> String {
    let values = values
        .iter()
        .map(|value| format!(r#"z.literal("{value}")"#))
        .collect::<Vec<_>>()
        .join(", ");
    format!("z.union([{values}])")
}

fn optional_meta() -> &'static str {
    "AcpMetaSchema.optional().nullable()"
}

fn optional_unknown() -> &'static str {
    "z.unknown().optional().nullable()"
}
