//! Transcript projection primitives for Conduit history windows.

use acp_core::{ConduitTerminalPlanData, TranscriptUpdateSnapshot};
use serde::{Deserialize, Serialize};
use serde_json::Value;

/// One projected transcript item for UI consumption.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(
    tag = "kind",
    rename_all = "snake_case",
    rename_all_fields = "camelCase"
)]
pub enum TranscriptItem {
    /// User or agent ACP content.
    Message {
        /// Stable item id within the loaded transcript.
        id: String,
        /// Prompt turn id when the item belongs to a live prompt turn.
        #[serde(skip_serializing_if = "Option::is_none")]
        turn_id: Option<String>,
        /// Live prompt item status when the item is part of a prompt turn.
        #[serde(skip_serializing_if = "Option::is_none")]
        status: Option<TranscriptItemStatus>,
        /// ACP stop reason for the completed turn, when known.
        #[serde(skip_serializing_if = "Option::is_none")]
        stop_reason: Option<String>,
        /// Message author role.
        role: MessageRole,
        /// ACP content blocks in transcript order.
        content: Vec<Value>,
    },
    /// Non-message provider update or Conduit-local event.
    Event {
        /// Stable item id within the loaded transcript.
        id: String,
        /// Prompt turn id when the item belongs to a live prompt turn.
        #[serde(skip_serializing_if = "Option::is_none")]
        turn_id: Option<String>,
        /// Live prompt item status when the item is part of a prompt turn.
        #[serde(skip_serializing_if = "Option::is_none")]
        status: Option<TranscriptItemStatus>,
        /// ACP stop reason for the completed turn, when known.
        #[serde(skip_serializing_if = "Option::is_none")]
        stop_reason: Option<String>,
        /// Whether this event came from provider ACP data or Conduit itself.
        source: TranscriptEventSource,
        /// Provider ACP update variant or Conduit-local event variant.
        variant: String,
        /// Structured event payload.
        data: Value,
    },
}

/// Source namespace for transcript events.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TranscriptEventSource {
    /// Event projected from provider ACP transcript data.
    Provider,
    /// Event generated by Conduit for local UI/history state.
    Conduit,
}

/// Status for prompt-turn transcript items.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TranscriptItemStatus {
    /// The item is complete.
    Complete,
    /// The item is still streaming.
    Streaming,
    /// The item was cancelled before normal completion.
    Cancelled,
    /// The item failed before normal completion.
    Failed,
}

/// Author role for projected transcript messages.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MessageRole {
    /// User-authored text.
    User,
    /// Agent-authored text.
    Agent,
}

/// Conduit-local transcript event to render inside one prompt turn.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConduitLocalTranscriptEvent {
    /// Conduit-local event variant.
    pub variant: String,
    /// Structured Conduit-local event payload.
    pub data: Value,
}

/// Projects provider transcript updates into UI transcript items.
#[must_use]
pub fn project_items(updates: &[TranscriptUpdateSnapshot]) -> Vec<TranscriptItem> {
    let mut updates = updates.to_vec();
    updates.sort_by_key(|update| update.index);
    let mut items = Vec::new();
    for update in updates {
        match text_role(&update) {
            Some((role, content)) => {
                append_content_item(&mut items, update.index, role, content);
                append_terminal_plan_event(&mut items, None, None, None, &update);
            }
            None => items.push(TranscriptItem::Event {
                id: format!("transcript-update-{}", update.index),
                turn_id: None,
                status: None,
                stop_reason: None,
                source: TranscriptEventSource::Provider,
                variant: update.variant.clone(),
                data: update.update.clone(),
            }),
        }
    }
    items
}

/// Projects live prompt-turn updates into UI transcript items.
#[must_use]
pub fn project_prompt_turn_items(
    turn_id: &str,
    updates: &[TranscriptUpdateSnapshot],
    conduit_events: &[ConduitLocalTranscriptEvent],
    status: TranscriptItemStatus,
    stop_reason: Option<&str>,
) -> Vec<TranscriptItem> {
    let mut updates = updates.to_vec();
    updates.sort_by_key(|update| update.index);
    let mut items = Vec::new();
    for update in updates {
        match text_role(&update) {
            Some((role, content)) => {
                append_prompt_content_item(
                    &mut items,
                    PromptContentItem {
                        turn_id,
                        role,
                        content,
                        update: &update,
                        status,
                        stop_reason,
                    },
                );
                append_terminal_plan_event(
                    &mut items,
                    Some(turn_id),
                    Some(status),
                    stop_reason,
                    &update,
                );
            }
            None => items.push(TranscriptItem::Event {
                id: format!("{turn_id}-update-{}", update.index),
                turn_id: Some(turn_id.to_owned()),
                status: Some(status),
                stop_reason: stop_reason.map(ToOwned::to_owned),
                source: TranscriptEventSource::Provider,
                variant: update.variant.clone(),
                data: update.update.clone(),
            }),
        }
    }
    append_conduit_prompt_events(&mut items, turn_id, conduit_events, status, stop_reason);
    items
}

fn append_conduit_prompt_events(
    items: &mut Vec<TranscriptItem>,
    turn_id: &str,
    conduit_events: &[ConduitLocalTranscriptEvent],
    status: TranscriptItemStatus,
    stop_reason: Option<&str>,
) {
    items.extend(
        conduit_events
            .iter()
            .enumerate()
            .map(|(index, event)| TranscriptItem::Event {
                id: format!("{turn_id}-conduit-event-{index}"),
                turn_id: Some(turn_id.to_owned()),
                status: Some(status),
                stop_reason: stop_reason.map(ToOwned::to_owned),
                source: TranscriptEventSource::Conduit,
                variant: event.variant.clone(),
                data: event.data.clone(),
            }),
    );
}

fn append_content_item(
    items: &mut Vec<TranscriptItem>,
    index: usize,
    role: MessageRole,
    content: Value,
) {
    if let Some(TranscriptItem::Message {
        role: existing_role,
        content: existing_content,
        ..
    }) = items.last_mut()
        && *existing_role == role
    {
        existing_content.push(content);
        return;
    }
    items.push(TranscriptItem::Message {
        id: format!("transcript-update-{index}"),
        turn_id: None,
        status: None,
        stop_reason: None,
        role,
        content: vec![content],
    });
}

struct PromptContentItem<'a> {
    turn_id: &'a str,
    role: MessageRole,
    content: Value,
    update: &'a TranscriptUpdateSnapshot,
    status: TranscriptItemStatus,
    stop_reason: Option<&'a str>,
}

fn append_prompt_content_item(items: &mut Vec<TranscriptItem>, input: PromptContentItem<'_>) {
    if let Some(TranscriptItem::Message {
        role: existing_role,
        content,
        stop_reason,
        ..
    }) = items.last_mut()
        && *existing_role == input.role
    {
        content.push(input.content);
        *stop_reason = input.stop_reason.map(ToOwned::to_owned);
        return;
    }
    let status = match input.role {
        MessageRole::User => TranscriptItemStatus::Complete,
        MessageRole::Agent => input.status,
    };
    items.push(TranscriptItem::Message {
        id: format!("{}-update-{}", input.turn_id, input.update.index),
        turn_id: Some(input.turn_id.to_owned()),
        status: Some(status),
        stop_reason: input.stop_reason.map(ToOwned::to_owned),
        role: input.role,
        content: vec![input.content],
    });
}

fn text_role(update: &TranscriptUpdateSnapshot) -> Option<(MessageRole, Value)> {
    let role = match update.variant.as_str() {
        "user_message_chunk" => MessageRole::User,
        "agent_message_chunk" => MessageRole::Agent,
        _ => return None,
    };
    let content = update.update.get("content")?.clone();
    Some((role, content))
}

fn append_terminal_plan_event(
    items: &mut Vec<TranscriptItem>,
    turn_id: Option<&str>,
    status: Option<TranscriptItemStatus>,
    stop_reason: Option<&str>,
    update: &TranscriptUpdateSnapshot,
) {
    let Some(data) = terminal_plan_data(update) else {
        return;
    };
    let id_prefix = turn_id.unwrap_or("transcript");
    items.push(TranscriptItem::Event {
        id: format!("{id_prefix}-update-{}-terminal-plan", update.index),
        turn_id: turn_id.map(ToOwned::to_owned),
        status,
        stop_reason: stop_reason.map(ToOwned::to_owned),
        source: TranscriptEventSource::Conduit,
        variant: "terminal_plan".to_owned(),
        data,
    });
}

fn terminal_plan_data(update: &TranscriptUpdateSnapshot) -> Option<Value> {
    let plan = update.update.pointer("/_meta/codex/terminalPlan")?;
    let item_id = plan.get("itemId").and_then(Value::as_str)?;
    let plan_text = plan.get("text").and_then(Value::as_str)?;
    let provider_source = plan.get("source").and_then(Value::as_str)?;
    if provider_source != "TurnItem::Plan" {
        return None;
    }
    if update
        .update
        .pointer("/content/text")
        .and_then(Value::as_str)?
        != plan_text
    {
        return None;
    }
    let data = ConduitTerminalPlanData::new(
        item_id.to_owned(),
        plan_text.to_owned(),
        provider_source.to_owned(),
        plan.get("turnId")
            .and_then(Value::as_str)
            .map(ToOwned::to_owned),
        plan.get("threadId")
            .and_then(Value::as_str)
            .map(ToOwned::to_owned),
    );
    serde_json::to_value(data).ok()
}

#[cfg(test)]
mod tests {
    use super::{
        MessageRole, TranscriptEventSource, TranscriptItem, TranscriptItemStatus, project_items,
        project_prompt_turn_items,
    };
    use acp_core::{ConduitTerminalPlanData, TranscriptUpdateSnapshot};
    use serde_json::{Value, json};
    use std::error::Error;

    type TestResult = Result<(), Box<dyn Error>>;

    #[test]
    fn adjacent_agent_message_chunks_project_to_one_message() -> TestResult {
        let items = project_prompt_turn_items(
            "turn-1",
            &[
                transcript_update(0, "agent_message_chunk", "fixture"),
                transcript_update(1, "agent_message_chunk", "-ready"),
            ],
            &[],
            TranscriptItemStatus::Complete,
            Some("end_turn"),
        );

        ensure_eq(&items.len(), &1usize, "item count")?;
        assert_agent_text(&items[0], "fixture-ready")
    }

    #[test]
    fn unknown_update_projects_to_event_item() -> TestResult {
        let items = project_items(&[TranscriptUpdateSnapshot {
            index: 4,
            variant: "tool_call".to_owned(),
            update: json!({ "sessionUpdate": "tool_call", "id": "tool-1" }),
        }]);

        ensure_eq(&items.len(), &1usize, "item count")?;
        let TranscriptItem::Event {
            source,
            variant,
            data,
            ..
        } = &items[0]
        else {
            return Err(format!("expected event item, got {:?}", items[0]).into());
        };
        ensure_eq(source, &TranscriptEventSource::Provider, "event source")?;
        ensure_eq(variant, &"tool_call".to_owned(), "event variant")?;
        ensure_eq(
            &data.get("id").and_then(Value::as_str),
            &Some("tool-1"),
            "event id",
        )
    }

    #[test]
    fn terminal_plan_meta_projects_agent_message_and_terminal_plan_event() -> TestResult {
        let items = project_prompt_turn_items(
            "turn-1",
            &[terminal_plan_update()],
            &[],
            TranscriptItemStatus::Complete,
            Some("end_turn"),
        );

        ensure_eq(&items.len(), &2usize, "terminal plan item count")?;
        assert_agent_message(&items[0])?;
        assert_terminal_plan_event(&items[1])
    }

    #[test]
    fn plain_agent_message_chunk_does_not_create_terminal_plan_event() {
        let items = project_prompt_turn_items(
            "turn-1",
            &[TranscriptUpdateSnapshot {
                index: 0,
                variant: "agent_message_chunk".to_owned(),
                update: json!({
                    "sessionUpdate": "agent_message_chunk",
                    "content": {
                        "type": "text",
                        "text": "normal markdown"
                    }
                }),
            }],
            &[],
            TranscriptItemStatus::Complete,
            None,
        );

        assert_eq!(items.len(), 1);
    }

    #[test]
    fn terminal_plan_meta_requires_turn_item_plan_source() {
        let items = project_prompt_turn_items(
            "turn-1",
            &[terminal_plan_update_with(json!({
                "source": "AgentMessage::FinalAnswer",
                "text": "# Plan\n",
                "itemId": "item-plan",
                "turnId": "codex-turn",
                "threadId": "codex-thread"
            }))],
            &[],
            TranscriptItemStatus::Complete,
            None,
        );

        assert_eq!(items.len(), 1);
    }

    #[test]
    fn terminal_plan_meta_requires_visible_text_match() {
        let items = project_prompt_turn_items(
            "turn-1",
            &[terminal_plan_update_with(json!({
                "source": "TurnItem::Plan",
                "text": "# Different Plan\n",
                "itemId": "item-plan",
                "turnId": "codex-turn",
                "threadId": "codex-thread"
            }))],
            &[],
            TranscriptItemStatus::Complete,
            None,
        );

        assert_eq!(items.len(), 1);
    }

    fn transcript_update(index: usize, variant: &str, text: &str) -> TranscriptUpdateSnapshot {
        TranscriptUpdateSnapshot {
            index,
            variant: variant.to_owned(),
            update: json!({
                "sessionUpdate": variant,
                "content": { "type": "text", "text": text }
            }),
        }
    }

    fn ensure_eq<T>(actual: &T, expected: &T, label: &str) -> TestResult
    where
        T: std::fmt::Debug + PartialEq,
    {
        if actual == expected {
            return Ok(());
        }
        Err(format!("{label}: expected {expected:?}, got {actual:?}").into())
    }

    fn terminal_plan_update() -> TranscriptUpdateSnapshot {
        terminal_plan_update_with(json!({
            "source": "TurnItem::Plan",
            "text": "# Plan\n",
            "itemId": "item-plan",
            "turnId": "codex-turn",
            "threadId": "codex-thread"
        }))
    }

    fn terminal_plan_update_with(plan: Value) -> TranscriptUpdateSnapshot {
        TranscriptUpdateSnapshot {
            index: 0,
            variant: "agent_message_chunk".to_owned(),
            update: json!({
                "sessionUpdate": "agent_message_chunk",
                "content": { "type": "text", "text": "# Plan\n" },
                "_meta": {
                    "codex": {
                        "terminalPlan": plan
                    }
                }
            }),
        }
    }

    fn assert_agent_text(item: &TranscriptItem, expected: &str) -> TestResult {
        let TranscriptItem::Message { content, role, .. } = item else {
            return Err(format!("expected message item, got {item:?}").into());
        };
        ensure_eq(role, &MessageRole::Agent, "message role")?;
        let text = content
            .iter()
            .filter_map(|block| block.get("text").and_then(Value::as_str))
            .collect::<String>();
        ensure_eq(&text, &expected.to_owned(), "message text")
    }

    fn assert_agent_message(item: &TranscriptItem) -> TestResult {
        let TranscriptItem::Message { content, role, .. } = item else {
            return Err(format!("expected message item, got {item:?}").into());
        };
        ensure_eq(role, &MessageRole::Agent, "message role")?;
        ensure_eq(
            &content[0].get("text").and_then(Value::as_str),
            &Some("# Plan\n"),
            "message text",
        )?;
        Ok(())
    }

    fn assert_terminal_plan_event(item: &TranscriptItem) -> TestResult {
        let TranscriptItem::Event {
            source,
            variant,
            data,
            status,
            stop_reason,
            ..
        } = item
        else {
            return Err(format!("expected terminal_plan event, got {item:?}").into());
        };
        ensure_eq(source, &TranscriptEventSource::Conduit, "event source")?;
        ensure_eq(variant, &"terminal_plan".to_owned(), "event variant")?;
        ensure_eq(
            status,
            &Some(TranscriptItemStatus::Complete),
            "event status",
        )?;
        ensure_eq(&stop_reason.as_deref(), &Some("end_turn"), "stop reason")?;
        ensure_str(data, "sessionUpdate", "terminal_plan")?;
        ensure_str(data, "interactionId", "terminal-plan:item-plan")?;
        ensure_str(data, "providerSource", "TurnItem::Plan")?;
        ensure_str(data, "planText", "# Plan\n")?;
        ensure_str(data, "codexTurnId", "codex-turn")?;
        ensure_str(data, "threadId", "codex-thread")?;
        serde_json::from_value::<ConduitTerminalPlanData>(data.clone())?;
        Ok(())
    }

    fn ensure_str(data: &Value, field: &str, expected: &str) -> TestResult {
        ensure_eq(
            &data.get(field).and_then(Value::as_str),
            &Some(expected),
            field,
        )
    }
}
