const CLIENT_PENDING_TIMEOUT_MS = 30_000;
const MAX_BUFFERED_BYTES = 1_048_576;
const MAX_FRAME_BYTES = 262_144;

const CLOSE_BUFFER_LIMIT = 1009;
const CLOSE_POLICY = 1008;
const CLOSE_REPLACED = 1012;

export {
  CLIENT_PENDING_TIMEOUT_MS,
  CLOSE_BUFFER_LIMIT,
  CLOSE_POLICY,
  CLOSE_REPLACED,
  MAX_BUFFERED_BYTES,
  MAX_FRAME_BYTES,
};
